cc_binary(
	  visibility = [
			"//visibility:public",
		],
    name = "bulkcopy",
		srcs = [
			  "main.cc",
		],
		deps = [
			  "@abseil-cpp//absl/log:check",
				"@abseil-cpp//absl/log:log",
			  "@abseil-cpp//absl/status:status",
				"//base:buffer",
		],
)

"""
cc_test(
	  name = "net_test",
		srcs = [
        "net_test.cc",
		],
		deps = [
			  "@googletest//:gtest",
				"@googletest//:gtest_main",
		]
)
"""
