cc_library(
	  visibility = [
			"//visibility:public",
		],
    name = "proxy",
		srcs = [
			  "main.cc",
		],
		deps = [
			  "@abseil-cpp//absl/log:check",
				"@abseil-cpp//absl/log:log",
			  "@abseil-cpp//absl/status:status",
				"//net",
		],
)
